Ages/urls.py
from django.urls import path
from . import views
from Ages.views import model_form_upload


app_name = 'Ages'

urlpatterns = [
    path('', model_form_upload, name='Ages'),

]

blog/urls.py
from django.urls import path
from . import views
from .views import blog, search, CategoryView, blogdetail

app_name='blog'

urlpatterns = [
path('blog/', blog.as_view(), name="blog"),
path('search/', search, name="search"),
path('category/<str:cats>/', CategoryView, name="category"),
path('<slug:slug>/send-comment', views.send_comment, name="send_comment"),
path('<slug:slug>/', blogdetail.as_view(), name="blog-detail"),
]

coralcity/urls.py
from django.contrib import admin
from django.urls import path,include
from graphene_django.views import GraphQLView
from blog.schema import schema
from pages import views
from listings import views
from accounts import views
from contacts import views
from Ages import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('listings/', include('listings.urls')),
    path('accounts/', include('accounts.urls')),
    path('contacts/', include('contacts.urls')),
    path('AgesVerification/', include('Ages.urls')),
    path('graphql/', GraphQLView.as_view(graphiql=True)),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


admin.site.site_header ="Koralcity control panel"
admin.site.index_title ="Administrators dashboard"
admin.site.site_title ="Control panel"

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, date
from django.db.models.base import Model
from django.db.models.signals import pre_save

from coralcity.utils import unique_slug_generator

# Create your models here.
class PostComment(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.sender.get_username()}'

class Categories(models.Model):
    categoryname = models.CharField(max_length=255)

    def __str__(self):
        return self.categoryname

class Post(models.Model):
    title = models.CharField(max_length=255)
    title_tag = models.CharField(max_length=255, default='Blog Post')
    slug = models.SlugField(max_length=255, null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='blog', null=True)
    body = models.TextField(blank=False, null=True)
    comments = models.ManyToManyField(PostComment, blank=True)
    post_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Categories, null=True, on_delete=models.PROTECT, related_name='category_set')

    def __str__(self):
        return self.title + ' | ' + str(self.author)

def slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(slug_generator, sender=Post)

blog/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView
from listings.choices import price_choices , bedroom_choices , state_choices
from listings.models import Listing
from .models import Post, Categories, PostComment
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseNotFound, Http404

# Create your views here.

def index(request):
   listings = Listing.objects.order_by('-list_date').filter(is_published=True);
   return render(request , 'pages/index.html',{'listings' : listings ,
        'state_choices' : state_choices,
        'bedroom_choices' : bedroom_choices,
        'price_choices' : price_choices,
        })

class blog(ListView):
   model = Post
   template_name = 'blog/blog_list.html'
   context_object_name = 'posts'
   cats = Categories.objects.all()

   ordering = ['-post_date']  
   paginate_by = 2

   def get_context_data(self, *args, **kwargs):
      cat_list = Categories.objects.all()
      latestpost_list = Post.objects.all().order_by('-post_date')[:3]
      context = super(blog, self).get_context_data(*args, **kwargs)
      context["cat_list"] = cat_list
      context["latestpost_list"] = latestpost_list
      return context


def search(request):
   template = 'blog/search_list.html'
   query = request.GET.get('q')
   if query:
      posts = Post.objects.filter(Q(title__icontains=query) | Q(body__icontains=query)).order_by('-post_date')
   else:
      posts = Post.objects.all()
   
   cat_list = Categories.objects.all()
   latestpost_list = Post.objects.all().order_by('-post_date')[:3]
   paginator = Paginator(posts, 2)
   page = request.GET.get('page')
   posts = paginator.get_page(page)
   return render(request, template, {'posts':posts, 'cat_list': cat_list, 'latestpost_list':latestpost_list, 'query':query})

def CategoryView(request, cats):
   if Categories.objects.filter(categoryname=cats).exists():
      category_posts = Post.objects.filter(category__categoryname=cats).order_by('-post_date')
      cat_list = Categories.objects.all()
      latestpost_list = Post.objects.all().order_by('-post_date')[:3]
      paginator = Paginator(category_posts, 2)
      page = request.GET.get('page')
      category_posts = paginator.get_page(page)
      return render(request, 'blog/category_list.html', {'cats':cats, 'category_posts':category_posts, 'cat_list': cat_list, 'latestpost_list':latestpost_list})
   else:
      raise Http404

class blogdetail(DetailView):
   model = Post
   template_name = 'blog/blog_detail.html'

   def get_context_data(self, *args, **kwargs):
      cat_list = Categories.objects.all()
      latestpost_list = Post.objects.all().order_by('-post_date')[:3]
      context = super(blogdetail, self).get_context_data(*args, **kwargs)
      context["cat_list"] = cat_list
      context["latestpost_list"] = latestpost_list
      return context

@login_required
def send_comment(request, slug):
   message = request.POST.get('message')
   post_id = request.POST.get('post_id')
   post_comment = PostComment.objects.create(sender=request.user, message=message)
   post = Post.objects.filter(id=post_id).first()
   post.comments.add(post_comment)
   return redirect('.')

templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
 <!-- Favicon -->
 <link href="https://fonts.googleapis.com/css?family=Grand+Hotel" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Fira+Sans:100,200,300,400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
  
  <link rel="stylesheet" href="{% static 'new/css/animate.css' %}">
  <link rel="stylesheet" href="{% static 'new/css/icomoon.css' %}">
  <link rel="stylesheet" href="{% static 'new/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'new/css/magnific-popup.css' %}">
  <link rel="stylesheet" href="{% static 'new/css/flexslider.css' %}">
  <link rel="stylesheet" href="{% static 'new/css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'new/css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'new/fonts/flaticon/font/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'new/css/style.css' %}">
  <script src="{% static 'new/js/modernizr-2.6.2.min.js' %}"></script>

      <!-- Favicon -->
      
    <link rel="icon" type="image/png" href="{% static './images/favicon.png' %}" />
    <link href="{% static './css/bootstrap.min.css' %}"  rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/lightbox.min.css' %}">

    <link rel="stylesheet" href="{% static 'new/style.css' %}"> 
    <link rel="icon" href="{% static 'new/img/core-img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'new/vendors/linericon/style.css' %}" />
    <link rel="stylesheet" href="{% static 'new/css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'new/vendors/owl-carousel/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'new/vendors/nice-select/css/nice-select.css' %}" />
    <link rel="stylesheet" href="{% static 'new/vendors/animate-css/animate.css' %}" />
    <link rel="stylesheet" href="{% static 'new/vendors/jquery-ui/jquery-ui.css' %}" />


    {% block title %}
    <title>Blog App</title>
    {% endblock %}
  </head>
<body>
    <header class="header-area">

        {% include 'partials/_navbar.html' %}
    </header>
    <!-- ##### Header Area End ##### -->



 
          {% block content %}
          {% endblock %}
          
</body>
          
       
     <!-- ##### Footer Area End ##### -->

    <!-- ##### All Javascript Script ##### -->
 <script src="{% static 'new/js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'new/js/bootstrap/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'new/js/bootstrap/bootstrap.min.js' %}"></script>
    <!-- All Plugins js -->
    <script src="{% static 'new/js/plugins/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'new/js/active.js' %}"></script>


  <!-- jQuery -->
  <script src="{% static 'new/js/jquery.min.js' %}"></script>
  <!-- jQuery Easing -->
  <script src="{% static 'new/js/jquery.easing.1.3.js' %}"></script>
  <!-- Bootstrap -->
  <script src="{% static 'new/js/bootstrap.min.js' %}"></script>
  <!-- Waypoints -->
  <script src="{% static 'new/js/jquery.waypoints.min.js' %}"></script>
  <!-- Flexslider -->
  <script src="{% static 'new/js/jquery.flexslider-min.js' %}"></script>
  <!-- Owl carousel -->
  <script src="{% static 'new/js/owl.carousel.min.js' %}"></script>
  <!-- Magnific Popup -->
  <script src="{% static 'new/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'new/js/magnific-popup-options.js' %}"></script>
  <!-- Main -->
  <script src="{% static 'new/js/main.js' %}"></script>

</html>

templates/blog/blog_detail.html
{% extends 'blog/base.html' %}
{% block title %}
<title>{{post.title_tag}}</title>
{% endblock %}
{% block content %}


<div id="colorlib-container">
      <div class="container">
        <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <article class="blog-entry">
              <div class="blog-wrap">
                <span class="category text-center"><a href="blog.html">Production:</a> | <a href="blog.html">{{post.category}}</a></span>
                <h2 class="text-center"><a href="blog.html">{{post.title}}</a></h2>
                <div class="blog-image">
                  <div class="owl-carousel owl-carousel2 blog-item">
                    <div class="item">
                      <a href="#" class="blog image-popup-link" style="background-image: url('{{post.img.url}}');">
                      </a>
                    </div>
                    <div class="item">
                      <a href="#" class="blog image-popup-link" style="background-image: url('{{post.img.url}}');">
                      </a>
                    </div>
                  </div>
                 
                </div>
                 <span class="category text-center"><a href=""><i class="icon-calendar3"></i> {{post.post_date | date:'d F y'}}</a> | <a href="" class="posted-by"><i class="icon-user2"></i> by {{post.author.first_name}}</a> | <a href=""><i class="icon-bubble3"></i> {{ post.comments.all.count }} Comments</a></span>
              <div class="desc">
                <p class="first-letra">{{post.body | safe}}</p>
               
              </div>
            </article>



{% if not request.user.is_authenticated %}
<div class="alert alert-danger">To comment, first <a href="">log in</a> to your account</div>
{% endif %}


  <div class="form-group">
    <form action="{% url 'blog:send_comment' post.slug %}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="post_id" value="{{ post.id }}">
      <textarea class="form-control" name="message" id="message" cols="30" rows="10" placeholder="Message"></textarea><br>
      <button type="submit" class="btn-primary btn-custom" style="background-color:#f6490d; border-color: #f6490d; font-style: normal;">Add Comment</button>
    </form>
  </div>


   <div class="comment-box">
     <h2 class="colorlib-heading-2">3 Comments</h2>
  {% for comment in post.comments.all %}
              <div class="comment-post">
                <div class="user"></div>
                <div class="desc">
                  <h3>{{ comment.sender.first_name}}<span>{{ comment.create_at }}</span></h3>
                  <p>{{ comment.message }}</p>
                </div>
              </div>
  {% empty %}
    </div>
    <div class="alert alert-danger">There is no comment</div>
  {% endfor %}
</div>

{% endblock %}

         

templates/blog/blog_list.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
 <div>
    <div id="colorlib-container">
      <div class="container">
          <div class="content">
{% for post in posts %}

            <article class="blog-entry">
              <div class="blog-wrap">
                <span class="category text-center"><a href="blog.html">Production:</a> | <a href="blog.html">{{post.category}}</a></span>
                <h2 class="text-center"><a href="{% url 'blog:blog-detail' post.slug %}">{{post.title}}</a></h2>
                <div class="blog-image">
                  <div class="owl-carousel owl-carousel2 blog-item">
                    <div class="item">
                      <a href="{% url 'blog:blog-detail' post.slug %}" class="blog image-popup-link" style="background-image: url('{{post.img.url}}');">
                      </a>
                    </div>
                    <div class="item">
                      <a href="{% url 'blog:blog-detail' post.slug %}" class="blog image-popup-link" style="background-image: url('{{post.img.url}}');">
                      </a>
                    </div>
                  </div>
                </div>
                <span class="category text-center"><a href=""><i class="icon-calendar3"></i> {{post.post_date | date:'d F y'}}</a> | <a href="" class="posted-by"><i class="icon-user2"></i> by {{post.author.first_name}}</a> | <a href=""><i class="icon-bubble3"></i> {{ post.comments.all.count }} Comments</a></span>
              </div>
              <div class="desc">
                <p class="first-letra">{{post.body | slice:':450' | safe}} </p>
              </div>
              <p class="text-center"><a href="{% url 'blog:blog-detail' post.slug %}" class="btn-primary btn-custom" style="background-color:#f6490d; border-color: #f6490d;">Continue Reading</a></p>
            </article>
           
           
    {% endfor %}
    <div>
          <nav aria-label="...">
            <ul class="pagination">
            {% if is_paginated %}
              {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" style="color:black" href="?page=1"><i class="fa fa-arrow-left" aria-hidden="true"></i></a></li>
                <li class="page-item"><a class="page-link" style="color:black" href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-left" aria-hidden="true"></i></a></li>
              {% endif %}
              {% for num in page_obj.paginator.page_range %}
                {% if num == page_obj.number %}
                  <li class="page-item active"><a class="page-link" style="color:#ffffff; background-color: black; border-color: black;" href="?page={{num}}">{{num}}</a></li>
                {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
                  <li class="page-item"><a class="page-link" style="color:black" href="?page={{num}}">{{num}}</a></li>
                {% endif %}
              {% endfor %}
              {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" style="color:black" href="?page={{page_obj.next_page_number}}"><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
                <li class="page-item"><a class="page-link" style="color:black" href="?page={{ page_obj.paginator.num_pages }}"><i class="fa fa-arrow-right" aria-hidden="true"></i></a></li>
              {% endif %}
            {% endif %}
            </ul>
          </nav>
          </div>
        </div>
        {% block sidebar %}
          <aside class="sidebar">
            <div class="side">
              <div class="form-group">
                <form action="{% url 'blog:search' %}" method="GET">
                <input type="text" class="form-control" name="q" value="{{request.GET.q}}" placeholder="Enter keywords &amp; hit enter....">
                <button type="submit" class="btn btn-primary"><i class="icon-search3"></i></button>
                </form>
              </div>
            </div>
            <div class="side-wrap">
              <h2 class="sidebar-heading">About Me</h2>
              <div class="author-img" style="background-image: url('https://images.unsplash.com/photo-1560179707-f14e90ef3623?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=873&q=80');"></div>
              <p> <strong>GovAwas Limited</strong> offers property owners, developers and buyers/renters a viable housing market. Customers can source and connect with professional agents for the most advanced and eco-friendly housing. Established in 2021, Koral City believes everyone deserves a home with the most advanced technology and Eco-Friendly means. All lives matter.</p>
              <p>
                <ul class="colorlib-social-icons">
                  <li><a href="#"><i class="icon-twitter"></i></a></li>
                  <li><a href="#"><i class="icon-facebook"></i></a></li>
                  <li><a href="#"><i class="icon-linkedin"></i></a></li>
                  <li><a href="#"><i class="icon-dribbble"></i></a></li>
                </ul>
              </p>
            </div>
            <div class="side-wrap">
              <h2 class="sidebar-heading">Recent Post</h2>

              {% for post in latestpost_list %}
              <div class="f-entry">
                <a href="{% url 'blog:blog-detail' post.slug %}" class="featured-img" style="background-image: url('{{post.img.url}}');"></a>
                <div class="desc">
                  <span><i class="icon-calendar3"></i> {{post.post_date| date:'d F y'}}</span>
                  <h3><a href="{% url 'blog:blog-detail' post.slug %}">{{post.title}}</a></h3>
                  <h3><a href="#"></a></h3>
                </div>
              </div>
              {% endfor %}
             
            </div>

            <div class="side-wrap">
              <h2 class="sidebar-heading">Categories</h2>
              <ul class="category">
                {% for categories in cat_list %}
                <li><a href="{% url 'blog:category' categories %}"><span class="badge bg-dark">{{categories.category_set.count}}</span><i class="icon-check"></i>{{categories}}</a> </li>
                    {% endfor %}
              </ul>
            </div>

        
            

            <div class="side-wrap">
              <h2 class="sidebar-heading">Tags</h2>
                <p class="tags">
                  <div class="button-cuz"><p>
                    {% for categories in cat_list %}
                      <span><a href="{% url 'blog:category' categories %}"><i class="icon-tag"></i>{{categories}}</a></span>
                       {% endfor %}
                    </p>
                  </div>
               </p>
            </div>

           
            <div class="side">
              <h2 class="sidebar-heading">Subscribe to our newsletter</h2>
              <div class="row">
                <div class="col-md-12 col-md-offset-0">
                  <div class="form-group">
                    <input type="text" class="form-control form-email text-center" id="email" placeholder="Enter your email">
                    <button type="submit" class="btn btn-primary btn-subscribe">Subscribe</button>
                  </div>
                </div>
                <p>
                  <ul class="colorlib-social-icons text-center">
                    <li><a href="#"><i class="icon-twitter"></i></a></li>
                    <li><a href="#"><i class="icon-facebook"></i></a></li>
                    <li><a href="#"><i class="icon-linkedin"></i></a></li>
                    <li><a href="#"><i class="icon-dribbble"></i></a></li>
                  </ul>
                </p>
              </div>
            </div>
          </aside> 
        </div>
      </div>
        {% endblock %}


{% endblock %}

templates/blog/category_list.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
 <div>
    <div id="colorlib-container">
      <div class="container">
          <div class="content">

{% for post in category_posts %}
 <article class="blog-entry">
              <div class="blog-wrap">
                <span class="category text-center"><a href="blog.html">Production:</a> | <a href="blog.html">{{post.category}}</a></span>
                <h2 class="text-center"><a href="{% url 'blog:blog-detail' post.slug %}">{{post.title}}</a></h2>
                <div class="blog-image">
                  <div class="owl-carousel owl-carousel2 blog-item">
                    <div class="item">
                      <a href="{% url 'blog:blog-detail' post.slug %}" class="blog image-popup-link" style="background-image: url('{{post.img.url}}');">
                      </a>
                    </div>
                    <div class="item">
                      <a href="{% url 'blog:blog-detail' post.slug %}" class="blog image-popup-link" style="background-image: url('{{post.img.url}}');">
                      </a>
                    </div>
                  </div>
                </div>
                <span class="category text-center"><a href="blog.html"><i class="icon-calendar3"></i> {{post.post_date | date:'d F y'}}</a> | <a href="blog.html" class="posted-by"><i class="icon-user2"></i> by {{post.author.first_name}}</a> | <a href="blog.html"><i class="icon-bubble3"></i> {{ post.comments.all.count }} Comments</a></span>
              </div>
              <div class="desc">
                <p class="first-letra">{{post.body | slice:':450' | safe}} </p>
              </div>
              <p class="text-center"><a href="{% url 'blog:blog-detail' post.slug %}" class=" btn-primary btn-custom" style="background-color:#f6490d; border-color: #f6490d;">Continue Reading</a></p>
            </article>
{% endfor %}

    <div>
         <nav aria-label="...">
  <ul class="pagination">
    {% if category_posts.has_previous %}
      <li class="page-item"><a class="page-link" style="color:black" href="?page=1"><i class="fa fa-arrow-left" aria-hidden="true"></i></a></li>
      <li class="page-item"><a class="page-link" style="color:black" href="?page={{ category_posts.previous_page_number }}"><i class="fa fa-angle-left" aria-hidden="true"></i></a></li>
    {% endif %}
    {% for num in category_posts.paginator.page_range %}
      {% if num == category_posts.number %}
        <li class="page-item active"><a class="page-link" style="color:#ffffff; background-color: black; border-color: black;" href="?page={{num}}">{{num}}</a></li>
      {% elif num > category_posts.number|add:'-2' and num < category_posts.number|add:'2' %}
        <li class="page-item"><a class="page-link" style="color:black" href="?page={{num}}">{{num}}</a></li>
      {% endif %}
    {% endfor %}
    {% if category_posts.has_next %}
      <li class="page-item"><a class="page-link" style="color:black" href="?page={{category_posts.next_page_number}}"><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
      <li class="page-item"><a class="page-link" style="color:black" href="?page={{ category_posts.paginator.num_pages }}"><i class="fa fa-arrow-right" aria-hidden="true"></i></a></li>
    {% endif %}
  </ul>
</nav>
          </div>
        </div>
        {% block sidebar %}
          <aside class="sidebar">
            <div class="side">
              <div class="form-group">
                <form action="{% url 'blog:search' %}" method="GET">
                <input type="text" class="form-control" name="q" value="{{request.GET.q}}" placeholder="Enter keywords &amp; hit enter....">
                <button type="submit" class="btn btn-primary"><i class="icon-search3"></i></button>
                </form>
              </div>
            </div>
            <div class="side-wrap">
              <h2 class="sidebar-heading">About Me</h2>
              <div class="author-img" style="background-image: url('/static/img/bg-img/about.jpg');"></div>
              <p> <strong>Dr. Samuel David Ocheja</strong> the presiding Bishop and founder of the Spirit of Life ministry International Incorporated and the senior Pastor of Green Pastures Assembly.  </p>
              <p>
                <ul class="colorlib-social-icons">
                  <li><a href="#"><i class="icon-twitter"></i></a></li>
                  <li><a href="#"><i class="icon-facebook"></i></a></li>
                  <li><a href="#"><i class="icon-linkedin"></i></a></li>
                  <li><a href="#"><i class="icon-dribbble"></i></a></li>
                </ul>
              </p>
            </div>
            <div class="side-wrap">
              <h2 class="sidebar-heading">Recent Post</h2>

              {% for post in latestpost_list %}
              <div class="f-entry">
                <a href="{% url 'blog:blog-detail' post.slug %}" class="featured-img" style="background-image: url('{{post.img.url}}');"></a>
                <div class="desc">
                  <span><i class="icon-calendar3"></i> {{post.post_date| date:'d F y'}}</span>
                  <h3><a href="{% url 'blog:blog-detail' post.slug %}">{{post.title}}</a></h3>
                  <h3><a href="#"></a></h3>
                </div>
              </div>
              {% endfor %}
             
            </div>

            <div class="side-wrap">
              <h2 class="sidebar-heading">Categories</h2>
              <ul class="category">
                {% for categories in cat_list %}
                <li><a href="{% url 'blog:category' categories %}"><span class="badge bg-dark">{{categories.category_set.count}}</span><i class="icon-check"></i>{{categories}}</a> </li>
                    {% endfor %}
              </ul>
            </div>

        
            <div class="side-wrap">
              <h2 class="sidebar-heading">Live stream</h2>
              {% for Livestream in Livestream %}
              <div class=" colorlib-video" style="background-image: url('{{ Livestream.Livestream_Image.url }}');">
                <a href="{{ Livestream.Livestream_URL }}" class="popup-vimeo"><i class="icon-play"></i></a>
                <div class="overlay"></div>
              </div>
              <h4 style="color: #000">{{ Livestream.Livestream_Title }}</h4>

               {% endfor %}
             </div>

            <div class="side-wrap">
              <h2 class="sidebar-heading">Tags</h2>
                <p class="tags">
                  <div class="button-cuz"><p>
                    {% for categories in cat_list %}
                      <span><a href="{% url 'blog:category' categories %}"><i class="icon-tag"></i>{{categories}}</a></span>
                       {% endfor %}
                    </p>
                  </div>
               </p>
            </div>
            <div class="side-wrap">
              <h2 class="sidebar-heading">Gallery</h2>
              <a href="{% static 'images/gallery-1.jpg' %}" class="gallery image-popup-link text-center" style="background-image: url( '/static/images/gallery-1.jpg');">
                <span><i class="icon-search3"></i></span>
              </a>
              <a href="{% static 'images/gallery-2.jpg' %}" class="gallery image-popup-link text-center" style="background-image: url('/static/images/gallery-2.jpg');">
                <span><i class="icon-search3"></i></span>
              </a>
              <a href="{% static 'images/gallery-3.jpg' %}" class="gallery image-popup-link text-center" style="background-image: url('/static/images/gallery-3.jpg');">
                <span><i class="icon-search3"></i></span>
              </a>
              <a href="{% static 'images/gallery-4.jpg' %}" class="gallery image-popup-link text-center" style="background-image: url('/static/images/gallery-4.jpg');">
                <span><i class="icon-search3"></i></span>
              </a>
              <a href="{% static 'images/gallery-5.jpg' %}" class="gallery image-popup-link text-center" style="background-image: url('/static/images/gallery-5.jpg');">
                <span><i class="icon-search3"></i></span>
              </a>
              <a href="{% static 'images/gallery-6.jpg' %}" class="gallery image-popup-link text-center" style="background-image: url('/static/images/gallery-6.jpg');">
                <span><i class="icon-search3"></i></span>
              </a>
              <a href="{% static 'images/gallery-7.jpg' %}" class="gallery image-popup-link text-center" style="background-image: url('/static/images/gallery-7.jpg');">
                <span><i class="icon-search3"></i></span>
              </a>
              <a href="{% static 'images/gallery-8.jpg' %}" class="gallery image-popup-link text-center" style="background-image: url('/static/images/gallery-8.jpg');">
                <span><i class="icon-search3"></i></span>
              </a>
            </div>
           
            <div class="side">
              <h2 class="sidebar-heading">Subscribe to our newsletter</h2>
              <div class="row">
                <div class="col-md-12 col-md-offset-0">
                  <div class="form-group">
                    <input type="text" class="form-control form-email text-center" id="email" placeholder="Enter your email">
                    <button type="submit" class="btn btn-primary btn-subscribe">Subscribe</button>
                  </div>
                </div>
                <p>
                  <ul class="colorlib-social-icons text-center">
                    <li><a href="#"><i class="icon-twitter"></i></a></li>
                    <li><a href="#"><i class="icon-facebook"></i></a></li>
                    <li><a href="#"><i class="icon-linkedin"></i></a></li>
                    <li><a href="#"><i class="icon-dribbble"></i></a></li>
                  </ul>
                </p>
              </div>
            </div>
          </aside> 
        </div>
      </div>
        {% endblock %}


{% endblock %}